# Generated by Django 3.2.7 on 2021-10-29 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=45)),
                ('industry', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Statements',
            fields=[
                ('statement_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
                ('multiplier', models.CharField(max_length=45)),
                ('company_key', models.ForeignKey(blank=True, db_column='company_key', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_fundamentals.companies')),
            ],
            options={
                'db_table': 'statements',
            },
        ),
        migrations.CreateModel(
            name='StatementRows',
            fields=[
                ('row_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_item', models.TextField()),
                ('row_nr', models.IntegerField()),
                ('style', models.CharField(blank=True, max_length=10, null=True)),
                ('statement_key', models.ForeignKey(blank=True, db_column='statement_key', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_fundamentals.statements')),
            ],
            options={
                'db_table': 'statement_rows',
            },
        ),
        migrations.CreateModel(
            name='RowData',
            fields=[
                ('row_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('row_key', models.ForeignKey(blank=True, db_column='row_key', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_fundamentals.statementrows')),
            ],
            options={
                'db_table': 'row_data',
            },
        ),
        migrations.CreateModel(
            name='Roic',
            fields=[
                ('roic_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('roic', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('company_key', models.ForeignKey(blank=True, db_column='company_key', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_fundamentals.companies')),
            ],
            options={
                'db_table': 'roic',
            },
        ),
        migrations.CreateModel(
            name='GrowthRates',
            fields=[
                ('growth_rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('growth_rate', models.CharField(max_length=25)),
                ('number_3y', models.DecimalField(blank=True, db_column='3Y', decimal_places=5, max_digits=10, null=True)),
                ('number_5y', models.DecimalField(blank=True, db_column='5Y', decimal_places=5, max_digits=10, null=True)),
                ('number_10y', models.DecimalField(blank=True, db_column='10Y', decimal_places=5, max_digits=10, null=True)),
                ('number_15y', models.DecimalField(blank=True, db_column='15Y', decimal_places=5, max_digits=10, null=True)),
                ('company_key', models.ForeignKey(blank=True, db_column='company_key', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_fundamentals.companies')),
            ],
            options={
                'db_table': 'growth_rates',
            },
        ),
    ]
